# Generated by Django 5.2.17 on 2026-09-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productvariantoption',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
