# Generated by Django 5.2.17 on 2026-09-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productattributevalue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate from the product and options.', max_length=100, unique=True),
        ),
    ]
