# Generated by Django 5.2.17 on 2026-09-17; hand-ordered so the data
# migration runs before the legacy image columns are removed.

import re

import apps.catalog.models
import apps.common.storages
import apps.common.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


_CLOUDINARY_RE = re.compile(
    r"^https?://res\.cloudinary\.com/[^/]+/image/upload/(?:v\d+/)?(.+?)(?:\.[A-Za-z0-9]+)?$"
)


def _name_from_url(value):
    """Best-effort Cloudinary delivery URL (or relative /media/ URL) -> storage name."""
    url = str(value or "").strip()
    match = _CLOUDINARY_RE.match(url)
    if match:
        return match.group(1)
    path = urlsplit(url).path if "://" in url else url
    if path.startswith("/media/"):
        return path[len("/media/") :]
    if "://" in url or " " in url or url.startswith("data:"):
        return ""
    return url


def migrate_image_names(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    ProductAttributeValue = apps.get_model("catalog", "ProductAttributeValue")
    ProductAttributeImage = apps.get_model("catalog", "ProductAttributeImage")

    for category in Category.objects.exclude(image="").iterator():
        category.image = _name_from_url(category.image)
        category.save(update_fields=["image", "updated_at"])

    for pav in ProductAttributeValue.objects.all().iterator():
        if str(pav.feature_image or ""):
            pav.feature_image = _name_from_url(pav.feature_image)
            pav.save(update_fields=["feature_image", "updated_at"])
        items = [item for item in (pav.additional_images or []) if isinstance(item, dict)]
        for order, item in enumerate(items):
            name = _name_from_url(item.get("url", ""))
            if not name:
                continue
            ProductAttributeImage.objects.create(
                product_attribute_value_id=pav.pk,
                image=name,
                title=item.get("title", "") or "",
                caption=item.get("caption", "") or "",
                alt=item.get("alt", "") or "",
                sort_order=order,
            )


def unmigrate_image_names(apps, schema_editor):
    ProductAttributeValue = apps.get_model("catalog", "ProductAttributeValue")
    for pav in ProductAttributeValue.objects.all().iterator():
        pav.additional_images = [
            {
                "url": str(image.image or ""),
                "title": image.title,
                "caption": image.caption,
                "alt": image.alt,
            }
            for image in pav.additional_images.all()
        ]
        pav.save(update_fields=["additional_images", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productvariant_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=apps.common.storages.image_storage, upload_to=apps.catalog.models.pav_additional_image_path, validators=[apps.common.validators.validate_image_upload])),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='catalog.productattributevalue')),
            ],
            options={
                'ordering': ['sort_order', 'created_at', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, storage=apps.common.storages.image_storage, upload_to=apps.catalog.models.category_image_path, validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='feature_image',
            field=models.ImageField(blank=True, storage=apps.common.storages.image_storage, upload_to=apps.catalog.models.pav_feature_image_path, validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.RunPython(migrate_image_names, unmigrate_image_names),
        migrations.RemoveField(
            model_name='category',
            name='image_public_id',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='feature_image_public_id',
        ),
    ]
