# Generated by Django 5.2.17 on 2026-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productattributeimage_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='currency',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
