# Generated by Django 5.2.17 on 2026-09-19 02:03

import apps.catalog.models
import apps.common.storages
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_productvariant_currency_productvariant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_image',
            field=models.ImageField(blank=True, help_text='Main product image shown in listings and detail views.', storage=apps.common.storages.image_storage, upload_to=apps.catalog.models.product_feature_image_path, validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_image_alt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_image_caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_image_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
