# Generated by Django 5.2.17 on 2026-09-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_feature_image_product_feature_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage_location',
            field=models.CharField(blank=True, choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside'), ('BOTH', 'Both')], default='BOTH', help_text='Where the product is intended to be used (Inside, Outside, or Both).', max_length=10),
        ),
    ]
