# Generated by Django 5.2.17 on 2026-09-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_usage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sole_type',
            field=models.CharField(blank=True, choices=[('LEATHER', 'Leather'), ('RUBBER', 'Rubber')], help_text='Type of sole material (Leather or Rubber).', max_length=10, null=True),
        ),
    ]
