# Generated by Django 5.2.17 on 2026-09-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_sole_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('UNISEX', 'Unisex'), ('KIDS', 'Kids'), ('BABY', 'Baby')], db_index=True, max_length=10, null=True),
        ),
    ]
