# Generated by Django 5.2.17 on 2026-09-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='Primary contact email address', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Primary phone number with country code (e.g., +977-1234567890)', max_length=50)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +977-1234567890)', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Physical address of the business')),
                ('map_url', models.URLField(blank=True, help_text='Google Maps URL or embedded map link', max_length=500)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', max_length=255)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', max_length=255)),
                ('tiktok_url', models.URLField(blank=True, help_text='TikTok profile URL', max_length=255)),
                ('pinterest_url', models.URLField(blank=True, help_text='Pinterest profile URL', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
                'db_table': 'cms_site_configuration',
            },
        ),
    ]
