# Generated by Django 5.2.17 on 2026-09-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_intro',
            field=models.TextField(blank=True, help_text='Company introduction or about us text'),
        ),
    ]
