# Generated by Django 5.2.17 on 2026-09-19 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_add_company_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SHIPPING', 'Shipping'), ('EXCHANGES_RETURNS', 'Exchanges & Returns'), ('PRIVACY_POLICY', 'Privacy Policy'), ('TERMS_CONDITIONS', 'Terms and Conditions')], db_index=True, help_text='Type of policy document', max_length=50, unique=True)),
                ('title', models.CharField(help_text="Policy title (e.g., 'Shipping Policy', 'Privacy Policy')", max_length=255)),
                ('content', models.TextField(help_text='Policy content in HTML format (from rich text editor)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is currently active and visible')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'cms_policy',
                'ordering': ['type'],
            },
        ),
    ]
