# Generated by Django 5.2.17 on 2026-09-19 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_add_policy_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMakers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Our Makers', help_text="Page title (e.g., 'Meet Our Makers', 'Our Team')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Introduction text about the makers/team')),
            ],
            options={
                'verbose_name': 'Our Makers',
                'verbose_name_plural': 'Our Makers',
                'db_table': 'cms_our_makers',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Team member's full name", max_length=255)),
                ('image', models.CharField(blank=True, help_text='Cloudinary image URL or reference name', max_length=500)),
                ('role', models.CharField(help_text="Job title or role (e.g., 'Master Craftsman', 'Designer')", max_length=255)),
                ('intro', models.TextField(help_text='Brief introduction or bio')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this member is currently displayed')),
                ('our_makers', models.ForeignKey(help_text='Our Makers page this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='cms.ourmakers')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'cms_team_member',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
