# Generated by Django 5.2.17 on 2026-09-19 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_add_our_makers'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Our Story', help_text='Main page title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Main introduction text')),
                ('section1_title', models.CharField(blank=True, help_text='Section 1 title', max_length=255)),
                ('section1_description', models.TextField(blank=True, help_text='Section 1 description')),
                ('section1_image', models.CharField(blank=True, help_text='Section 1 image (Cloudinary URL or reference)', max_length=500)),
                ('section2_title', models.CharField(blank=True, help_text='Section 2 title', max_length=255)),
                ('section2_description', models.TextField(blank=True, help_text='Section 2 description')),
                ('section2_image', models.CharField(blank=True, help_text='Section 2 image (Cloudinary URL or reference)', max_length=500)),
                ('section3_title', models.CharField(blank=True, default='Our Journey', help_text='Section 3 title (has subsections)', max_length=255)),
            ],
            options={
                'verbose_name': 'Our Story',
                'verbose_name_plural': 'Our Story',
                'db_table': 'cms_our_story',
            },
        ),
        migrations.CreateModel(
            name='StorySubsection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Subsection title', max_length=255)),
                ('image', models.CharField(blank=True, help_text='Subsection image (Cloudinary URL or reference)', max_length=500)),
                ('description', models.TextField(help_text='Subsection description')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subsection is currently displayed')),
                ('our_story', models.ForeignKey(help_text='Our Story page this subsection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='section3_subsections', to='cms.ourstory')),
            ],
            options={
                'verbose_name': 'Story Subsection',
                'verbose_name_plural': 'Story Subsections',
                'db_table': 'cms_story_subsection',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
