# Generated by Django 5.2.17 on 2026-09-19 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_add_our_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurSustainability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Our Sustainability', help_text='Page title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Introduction text about sustainability commitment')),
            ],
            options={
                'verbose_name': 'Our Sustainability',
                'verbose_name_plural': 'Our Sustainability',
                'db_table': 'cms_our_sustainability',
            },
        ),
        migrations.CreateModel(
            name='SustainabilitySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Section title', max_length=255)),
                ('description', models.TextField(help_text='Section description')),
                ('image', models.CharField(blank=True, help_text='Section image (Cloudinary URL or reference)', max_length=500)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is currently displayed')),
                ('our_sustainability', models.ForeignKey(help_text='Our Sustainability page this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.oursustainability')),
            ],
            options={
                'verbose_name': 'Sustainability Section',
                'verbose_name_plural': 'Sustainability Sections',
                'db_table': 'cms_sustainability_section',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
