# Generated by Django 5.2.17 on 2026-09-19 07:26

import apps.cms.models
import apps.common.storages
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_add_our_sustainability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstory',
            name='section1_image',
            field=models.ImageField(blank=True, help_text='Section 1 image', null=True, storage=apps.common.storages.image_storage, upload_to=apps.cms.models.story_image_path, validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='section2_image',
            field=models.ImageField(blank=True, help_text='Section 2 image', null=True, storage=apps.common.storages.image_storage, upload_to=apps.cms.models.story_image_path, validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='storysubsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Subsection image', null=True, storage=apps.common.storages.image_storage, upload_to=apps.cms.models.story_subsection_image_path, validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='sustainabilitysection',
            name='image',
            field=models.ImageField(blank=True, help_text='Section image', null=True, storage=apps.common.storages.image_storage, upload_to=apps.cms.models.sustainability_section_image_path, validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, help_text='Team member photo', null=True, storage=apps.common.storages.image_storage, upload_to=apps.cms.models.team_member_image_path, validators=[apps.common.validators.validate_image_upload]),
        ),
    ]
