# Generated by Django 5.2.17 on 2026-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_convert_images_to_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstory',
            name='section1_description',
            field=models.TextField(blank=True, default='', help_text='Section 1 description'),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='section1_image',
            field=models.CharField(blank=True, default='', help_text='Section 1 image URL (Cloudinary)', max_length=500),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='section2_description',
            field=models.TextField(blank=True, default='', help_text='Section 2 description'),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='section2_image',
            field=models.CharField(blank=True, default='', help_text='Section 2 image URL (Cloudinary)', max_length=500),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='section2_title',
            field=models.CharField(blank=True, default='', help_text='Section 2 title', max_length=255),
        ),
        migrations.AlterField(
            model_name='storysubsection',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Subsection image URL (Cloudinary)', max_length=500),
        ),
        migrations.AlterField(
            model_name='sustainabilitysection',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Section image URL (Cloudinary)', max_length=500),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Team member image URL (Cloudinary)', max_length=500),
        ),
    ]
