# Generated by Django 5.2.17 on 2026-09-19 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_revert_to_charfield_for_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section1_tag', models.CharField(blank=True, default='', help_text='Section 1 tag/label', max_length=100)),
                ('section1_image', models.CharField(blank=True, default='', help_text='Section 1 image URL (Cloudinary)', max_length=500)),
                ('section1_title', models.CharField(blank=True, default='', help_text='Section 1 title', max_length=255)),
                ('section1_description', models.TextField(blank=True, default='', help_text='Section 1 description')),
                ('section1_quote', models.TextField(blank=True, default='', help_text='Section 1 quote')),
                ('section2_tag', models.CharField(blank=True, default='', help_text='Section 2 tag/label', max_length=100)),
                ('section2_title', models.CharField(blank=True, default='', help_text='Section 2 title', max_length=255)),
                ('section2_description', models.TextField(blank=True, default='', help_text='Section 2 description')),
                ('section2_image', models.CharField(blank=True, default='', help_text='Section 2 image URL (Cloudinary)', max_length=500)),
                ('section2_features', models.JSONField(blank=True, default=list, help_text='Array of feature objects with title and intro')),
                ('section3_tag', models.CharField(blank=True, default='', help_text='Section 3 tag/label', max_length=100)),
                ('section3_title', models.CharField(blank=True, default='', help_text='Section 3 title', max_length=255)),
                ('section3_image', models.CharField(blank=True, default='', help_text='Section 3 image URL (Cloudinary)', max_length=500)),
                ('section3_description', models.TextField(blank=True, default='', help_text='Section 3 description')),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
                'db_table': 'cms_homepage',
            },
        ),
        migrations.CreateModel(
            name='HomepageCollections',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, default='', help_text='Collections section tag/label', max_length=100)),
                ('title', models.CharField(default='Our Collections', help_text='Collections section title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Collections section description')),
            ],
            options={
                'verbose_name': 'Homepage Collections',
                'verbose_name_plural': 'Homepage Collections',
                'db_table': 'cms_homepage_collections',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(blank=True, default='', help_text='Collection image URL (Cloudinary)', max_length=500)),
                ('name', models.CharField(help_text='Collection name', max_length=255)),
                ('intro', models.TextField(help_text='Collection introduction/description')),
                ('link', models.CharField(help_text='Internal link path (e.g., /inside, /outdoor)', max_length=255)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this collection is currently displayed')),
                ('homepage_collections', models.ForeignKey(help_text='Homepage Collections page this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='cms.homepagecollections')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'db_table': 'cms_collection',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
