# Generated by Django 5.2.17 on 2026-09-19 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_add_homepage_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether subscription is active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='Subscription date')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'cms_subscription',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
