# Generated by Django 5.2.17 on 2026-09-19 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_add_subscription_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Sender's full name", max_length=255)),
                ('email', models.EmailField(help_text="Sender's email address", max_length=255)),
                ('phone', models.CharField(blank=True, default='', help_text="Sender's phone number (optional)", max_length=50)),
                ('subject', models.CharField(help_text='Message subject', max_length=255)),
                ('message', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', help_text='Message status', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal admin notes')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'cms_contact_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
